# from https://github.com/Flexiana/framework/blob/main/.github/workflows/test.yml
name: Clojure CI

on:
  push:
    branches: '!main'
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@9.4
      with:
        # Install just one or all simultaneously
        # The value must indicate a particular version of the tool, or use 'latest'
        # to always provision the latest version
        cli: 1.11.1.1155              # Clojure CLI based on tools.deps

    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.deps.clj
        # List all files containing dependencies:
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Run cljstyle
      run: clojure -M:run/cljstyle check

    - name: Run tests
      run: clojure -M:run/test
